#!/bin/sh

## Wrapper script to launch xterm and connect with a browser-based X11 server

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
MOUNT_DIR=${1:-`pwd`}
XPRA_DEFAULTS="$SCRIPT_DIR/util/xpra-default-settings.txt"
XPRA_DEFAULTS_MOUNT=""

if [ -f "$XPRA_DEFAULTS" ]; then
  XPRA_DEFAULTS_MOUNT="-v $XPRA_DEFAULTS:/usr/share/xpra/www/default-settings.txt:ro"
fi

# NOTE: apptainer forwards all ports by default
apptainer run --cleanenv --writable-tmpfs \
    --bind "$MOUNT_DIR:/home/vscode/data" \
    --pwd /home/vscode \
    ${XPRA_DEFAULTS_MOUNT:+--bind "$XPRA_DEFAULTS:/usr/share/xpra/www/default-settings.txt:ro"} \
    docker://ghcr.io/amrex-codes/amrvis-container:main

## open your web browser to http://localhost:8080
## enter the autogenerated password printed to the terminal
## type `amrvis2d' or `amrvis3d' in order to launch amrvis
