#!/bin/sh

## Wrapper script to launch xterm and connect with a browser-based X11 server

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
MOUNT_DIR=${1:-`pwd`}
XPRA_DEFAULTS="$SCRIPT_DIR/util/xpra-default-settings.txt"
XPRA_DEFAULTS_MOUNT=""

if [ -f "$XPRA_DEFAULTS" ]; then
  XPRA_DEFAULTS_MOUNT="-v $XPRA_DEFAULTS:/usr/share/xpra/www/default-settings.txt:ro"
fi

port=8080
submit_host=${SLURM_SUBMIT_HOST:-$HOSTNAME}
compute_host=${SLURMD_NODENAME:-$HOSTNAME}
default_image="docker://ghcr.io/amrex-codes/amrvis-container:main"
local_sif="$SCRIPT_DIR/amrvis-container.sif"
image="${AMRVIS_APPTAINER_IMAGE:-$default_image}"
pull_cmd="apptainer pull $local_sif $default_image"

if command -v srun >/dev/null 2>&1 && [ -z "$SLURM_JOB_ID" ]; then
  echo "Detected SLURM environment on host $HOSTNAME, but no interactive job is active."
  echo "Please start an interactive job and re-run this script, for example:"
  echo "  salloc -N 1 -t 01:00:00"
  echo "or"
  echo "  srun -N 1 -t 01:00:00"
  exit 1
fi

if [ -n "$SLURM_JOB_ID" ]; then
  if [ -n "$AMRVIS_APPTAINER_IMAGE" ]; then
    image="$AMRVIS_APPTAINER_IMAGE"
  elif [ -f "$local_sif" ]; then
    image="$local_sif"
  else
    echo "ERROR: SLURM interactive job detected, but no local SIF was found at $local_sif."
    echo "Exit this interactive job and pull the image from a login node with:"
    echo "  $pull_cmd"
    exit 1
  fi

  if [ ! -f "$image" ]; then
    echo "ERROR: SLURM interactive job detected, but the image file '$image' does not exist."
    echo "If you want to use the default image, exit this job and pull it on a login node with:"
    echo "  $pull_cmd"
    exit 1
  fi
fi
echo
echo
echo "Launching Amrvis-container with port $port on $HOSTNAME"
echo
echo "Your SSH tunnel command on your desktop should look like the following"
echo
if [ -n "$SLURM_JOB_ID" ]; then
  echo "  ssh -L 9999:${compute_host}:${port} $USER@${submit_host}"
  echo
  echo "(Detected SLURM interactive job: job $SLURM_JOB_ID, submit host ${submit_host}, compute host ${compute_host})"
else
  echo "  ssh -L 9999:$HOSTNAME:$port $USER@$submit_host"
fi
echo
echo "Then visit http://localhost:9999 on your desktop."
echo
echo "To terminate this session press ctrl-C twice."
echo
echo "Using Apptainer image: $image"
echo

# NOTE: apptainer forwards all ports by default
apptainer run --cleanenv --writable-tmpfs \
    --bind "$MOUNT_DIR:/home/vscode/data" \
    --bind "$SCRIPT_DIR/util/start_http_server.sh:/home/vscode/start_http_server.sh:ro" \
    --env APPTAINERENV_SHELL=/bin/bash \
    --env APPTAINERENV_BASH_ENV=/home/vscode/.bashrc \
    --pwd /home/vscode \
    ${XPRA_DEFAULTS_MOUNT:+--bind "$XPRA_DEFAULTS:/usr/share/xpra/www/default-settings.txt:ro"} \
    "$image"

## open your web browser to http://localhost:8080
## enter the autogenerated password printed to the terminal
## type `amrvis2d' or `amrvis3d' in order to launch amrvis
