#!/bin/sh

## Wrapper script to launch xterm and connect with a browser-based X11 server

MOUNT_DIR=${1:-`pwd`}

docker run --init -p 8080:8080 --platform linux/amd64 -v $MOUNT_DIR:/home/vscode/data ghcr.io/benwibking/amrvis-container:latest

## open your web browser to http://localhost:$PORT
## enter the autogenerated password printed to the terminal
## type `amrvis2d' or `amrvis3d' in order to launch amrvis
