#!/bin/sh

## Wrapper script to launch browser-based X11 session
## (NOTE: This should only be called from within the Docker container.)
PORT=8080
EXE=xterm
export XPRA_PASSWORD=$(openssl rand -hex 16)

echo ""
echo ""
echo "************************************************************"
echo "Starting xpra server on http://localhost:$PORT/"
echo "Autogenerated password: $XPRA_PASSWORD"
echo "************************************************************"
echo ""
echo ""

xpra start --start=$EXE --bind-tcp=0.0.0.0:$PORT --ssl-cert=/etc/xpra/ssl-cert.pem --no-daemon

## open your web browser to http://localhost:$PORT
## enter the autogenerated password printed to the terminal
## type `amrvis2d' or `amrvis3d' in order to launch amrvis
