#!/bin/sh

## Wrapper script to launch browser-based X11 session
## (NOTE: This should only be called from within the Docker container.)
PORT=8080
EXE=xterm
#EXE=/Amrvis3D/amrvis3d.gnu.ex
export XPRA_PASSWORD=$(openssl rand -hex 16)

echo ""
echo ""
echo "************************************************************"
echo "Starting xpra server on http://localhost:$PORT/"
echo "Autogenerated password: $XPRA_PASSWORD"
echo "************************************************************"
echo ""
echo ""

xpra start --start=$EXE --bind-tcp=0.0.0.0:$PORT --ssl-cert=/etc/xpra/ssl-cert.pem --no-daemon
